name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: install libusb
      run: wget https://github.com/libusb/libusb/archive/v1.0.24.zip && unzip v1.0.24.zip
    - name: write local properties
      run: echo "libusb.dir=$GITHUB_WORKSPACE/libusb-1.0.24" > $GITHUB_WORKSPACE/local.properties
    - name: Build & test with Gradle
      run: ./gradlew jacocoTestReport --stacktrace
    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
